name: fleer_relay
publish_to: none
repository: https://github.com/johan-perso/fleer-relay

environment:
  sdk: ^3.12.0

dependencies:
  dotenv: 4.2.0
  nanoid2: 2.0.1
  shelf: 1.4.2
  shelf_router: 1.1.4
  shelf_multipart: 2.0.1
  shelf_web_socket: 3.0.0
  web_socket_channel: 3.0.3
  system_info3: 4.0.2
